# Use an official debian as parent image
FROM debian:stable

RUN mkdir -p /usr/sbin/ && mkdir -p /etc/

# Setup Spread
COPY res/bin/armhf/spread /usr/sbin/
COPY res/etc/spread.conf /etc/

# Make spread port available
EXPOSE 4803

# Create spread user because spread will not start as root
RUN groupadd -r spread && useradd --no-log-init -r -g spread spread
USER spread
WORKDIR /home/spread

# Start spread using the default configuration
CMD exec spread
